### ISSUE TITLE
FlowSOM populations not exported into FlowJo

### ISSUE THREAD

**Issue by rosasott** [SofieVG/FlowSOM#12]
Hi! I'm having an issue trying to use FlowSOM in FlowJo. Basically I don't get any population after applying the plugin. The R path looks fine, but other that a CSV file I don't get anything else. I'm attaching an image with the result in FlowJo. Can somebody help? Thanks!!!

<img width="887" alt="screen shot 2018-06-29 at 4 58 38 pm" src="https://user-images.githubusercontent.com/40703556/42114651-c36cb218-7bbd-11e8-9d1f-5317b727dcb5.png">

I want to present some fancy data next week! ;-)

**Comment by SofieVG** [comment]
Hi,

If there is only a csv file and nothing else in the FlowSOM directory, I'm
afraid it might be your connection to R which is not set up as it should
be. Make sure to check the checkbox to save the script, this will help
debugging if the script is called. If you see no script at all, try if any
of the other R dependent plugins is working. If these also don't work, it
might be best to contact Flowjo support. Also double check there are no
spaces anywhere in the path where you save your workspace! Eg in the
screenshot you share, you might need to add underscores instead of spaces
in your filename.

Kind regards,
Sofie

**Comment by rosasott** [comment]
Hi,
thanks for the answer! I tried and also other R dependent plugins don't work. I will contact FlowJo support. If I find the solution I'll post it here before to close the issue.

**Comment by SarahL449** [comment]
Hi,

I do have exactly the same problem and I don't find the answer...In fact, it works when I have only one sample, and that I take all the markers that I have (so without any "pre-gating"). If you finally had found a solution, please help me :)

Kind regards,
Sarah

**Comment by judithfraussen** [comment]
Hi,

I also do not get populations in FlowJo when running FlowSOM. I do see a lot of files in the FlowSOM directory, including a .rout file for the script. Do you know if this is a problem related to FlowSOM or FlowJo?

Kind regards,
Judith

**Comment by SofieVG** [comment]
Hi Judith,

If you see the .rout file, it might be a FlowSOM/R problem. Could you send
me the .Rout file so I can take a look if it contains an error that might
tell us more about what is going on?

Kind regards,
Sofie

**Comment by mariavon** [comment]
Hello,
I use the FlowSOM plugin in FlowJo 10.6 and it was working fine until last week.  Now, when I try to run flowSOM on a population it does not calculate the metaclusters.  I uninstalled both R and FlowJo and then installed again but nothing changed. I see a cvs file and an R script in the FlowSOM folder. Do you know where the problem could be? Many thanks.
Best,
Maria

![FlowSom_issues](https://user-images.githubusercontent.com/52401738/68291993-48335800-008b-11ea-9373-32f1a9750c29.png)
 do not see the populations

**Comment by SofieVG** [comment]
Could you have a look at the Rscript.flowSOM...R file and see if any error
is reported? It might have to do with the latest bioconductor update if you
recently reinstalled everything.

Kind regards,
Sofie

**Comment by emma2121** [comment]
@SofieVG I'm having the same issue as @mariavon :
  
When I try to use the FlowSOM plug-in with FlowJo version 10.6.1, populations are not generated. There is an RScript and csv file generated in the FlowSOM file but no new FCS Files. On the FlowJo workspace itself, the "FlowSOM" image appears but no Metaclusters or mapping image is attached to it. I recently got a new computer, and this is my first time attempting to use FlowSOM on this computer, but had previously used it without issue. I downloaded FlowSOM v2.5 from the FlowJo Exchange and followed the How to FlowSOM pdf document. 

Please see screenshot for FlowJo Workspace, FlowSOM folder, and RScript output. I'd appreciate any advice you have on how to troubleshoot this!

Thank you,
Emma
<img width="1662" alt="Screen Shot 2019-12-02 at 7 48 15 PM" src="https://user-images.githubusercontent.com/48060540/70006934-b4936100-153c-11ea-9026-1b6673267e74.png">

**Comment by SofieVG** [comment]
Dear Emma,

Unfortunately, from the R script it is hard to see where it could go wrong.
Previously, FlowJo stored a transcript from the run, also showing the
output of all these calls, that made it easier to spot errors. To ensure
that FlowSOM is correctly installed on your computer, can you try to run
the piece of example code below? If this works, I think it might be better
to reach out to FlowJo for further help. If this returns some error, please
let me know which error exactly is shown.

Kind regards,
Sofie


fileName <- system.file("extdata", "68983.fcs", package="FlowSOM")
ff <- flowCore::read.FCS(fileName)
ff <- flowCore::compensate(ff,ff@description$SPILL)
ff <- flowCore::transform(ff,
                          flowCore::transformList(colnames(ff@description
$SPILL),

flowCore::logicleTransform()))
flowSOM.res <- FlowSOM(ff, scale = TRUE, colsToUse = c(9,12,14:18), nClus =
10, seed = 1)
PlotStars(flowSOM.res[[1]])

**Comment by emma2121** [comment]
@SofieVG Thank you so much for your response! Apparently FlowSOM is not correctly installed on my computer because I received the following error messages: 

**Error in FlowSOM(ff, scale = TRUE, colsToUse = c(9, 12, 14:18), nClus = 10,  : 
  could not find function "FlowSOM"**

**Error in PlotStars(flowSOM.res[[1]]) : 
  could not find function "PlotStars"**

When I downloaded the packages, I receive the following message on their location: 

**The downloaded binary packages are in
	/var/folders/kt/5_hh_ysx49b22xrs3gtz7r940000gn/T//Rtmp1E8QWW/downloaded_packages**

Should they be installing in a different location? 

I really appreciate your help on this. 

All the best,
Emma

**Comment by emma2121** [comment]
@SofieVG Ignore that prior message! I forgot to attach the package to my workspace! The code that you sent me worked totally fine. I will contact FlowJo. 

Thank you so much for your help!

**Comment by jardplard** [comment]
Hi, I am having the same issue as @emma2121 and others, in that my populations are not showing up despite successful R and .csv files being generated (other R-based plugins are also not working). I also tried running the code you listed above, and got the same error message that was originally noted. It seems that @emma2121 was able to resolve the issue by attaching the package to the workspace, but I am not sure what this means/how to complete this. Any help would be greatly appreciated!

**Comment by UlfKlan** [comment]
I had the same issue. Realised that the correct R-path is C:\Program Files\R\R-3.6.0\bin and not only C:\Program Files\R\R-3.6.0 as i started out with. Hope this help someone.

**Comment by harshininsriram** [comment]
Hi,

@UlfKlan I faced the same issue as you. Changed the R-path to C:\Program Files\R\R-3.6.0\bin. FlowSom now works as it should. Thank you for the help!

**Comment by nataliatusia** [comment]
Hi all! 

I recently found out FlowSOM and I got really enthousiastic about using it! Your discussion on this issue really helped me figuring out how it works (thank you for that!), unfortunately while running flowSOM on a population it also doesn't calculate the metaclusters. I tried running the piece of example code given by @SofieVG and this works. I also tried to change the R-path to C:\Program Files\R\R-4.0.3\bin but it does not help in solving the issue. 
What else could I try to make it work?

Kind regards,
Natalia

**Comment by UlfKlan** [comment]
@nataliatusia Its hard to say. One issue i encountered was resolved by following. after installing the packages in R i opened R-studio and loaded/checked the flowcore, flowsom, igraph and pheatmap packages. Some of them would not load because R lacked other packeges. After installing these packages the plugin worked fine. So this could be something to try. 

Besides before you run the plugin be sure to save the workspace, and if you want to rerun the plugin on the same population, make sure to either rename the workspace and save, or delete both the flowsom folder created by last run and al flowsom nodes in flowjo, otherwise your output will be corrupted. eg. insisting on giving you 6 metaclusters as in your first run despite chosing 10 and some populations might be empty.

**Comment by SofieVG** [comment]
Hi @nataliatusia,

I think if the example code is working and you see the FlowSOM figure when executing that code, the installation in R is probably correct and the issue will be related to the connection between FlowJo and R. Unfortunately, I can't really help with that, maybe you could reach out to the FlowJo support?

All the best,
Sofie

**Comment by yk923** [comment]
H there, 
I am interested in FlowSOM in flowjo, may I ask how to ensure same orientation of the mapping? I found out that there is error in the "apply on mapping" that I could not select a particular group and so everytime the flowsom will create a different map....

Regards,
Yvonne

**Comment by SofieVG** [comment]
Hi @yk923,

Do you mean you can't see any previous options in the "Apply on map" dropdown, are not able to select the option you want, or when selecting the option that it still creates a new map? See https://www.youtube.com/watch?v=Kj8RuSz2jEI for some guidance from FlowJo, e.g. around 17:50 the apply on map option is selected. 

As I did not develop the FlowJo plugin myself, you might be more successful requesting help from the FlowJo helpdesk.

As a sidenote, I am not entirely sure that the FlowJo plugin is completely updated to the latest version of FlowSOM here on the github, it might cooperate better when installing from bioconductor if you want to have it integrated in FlowJo. However, I'm not sure if that would be the issue here, as I think it would already give an error much earlier in the process. 


All the best,
Sofie

**Comment by mirredb** [comment]
Hi everyone, 

I'm analyzing my data with FlowSOM for a while, but always get the same error. When I run flowSOM on my total population, it works fine. Once I want to run FlowSOM on a subset of data, applied on the map that was generated with the total data, I get only a CSV file as output, and no pdf/images (see image). Does anyone know how to fix this? 
![error](https://user-images.githubusercontent.com/80685473/111146194-70896b80-8589-11eb-9e7b-c9b525c2409b.jpg)

Many thanks, 
Mirre

**Comment by lisandy123** [comment]
I had this same problem but resolved with the help of FlowJo support.
Here is some of their reply, I think it will help for some people experiencing the same problem:
"Please make sure that there are not non-ACSII characters (@ , # % ^ & * ! é ü ) in the file path leading up to the workspace or FCS files. Non-English characters would also cause this issue.

Issues can occur when the .wsp or .fcs files being used in the workspace are stored on a server. This is because the computer can often have poor or inconsistent connection to files stored in remote locations or lack the permissions to access these locations. If the files are stored on a server, I would try moving them locally (ie to the Documents folder of your C drive user account location) and see if that helps. 

Alternatively, you could also save the workspace as an .acs file (Save as Archive). When FlowJo opens an .acs file it creates a local cache for the analysis so it does not need to constantly reference the data on the server. Below is a link to more information on using FlowJo with a remote drive. "
