### ISSUE TITLE
Transposed the metaclusterMFI result!!

### ISSUE THREAD

**Issue by SamGG** [SofieVG/FlowSOM#13]
Hi. Thanks for updating the package. I have just read this major change. Although it only targets the meta clustering, I wonder how much it will impact packages (such as cytofkit) and analyses that depend on it.
Best.

**Comment by SofieVG** [comment]
Good point, I will check. 
However, I think the impact will be limited, as this function was not available on bioconductor yet. It seems more logical to me to keep the markers as columns instead of suddenly having them as rows, so if it does not negatively influence other packages, I would prefer to keep it the new way.

**Comment by SamGG** [comment]
Good point, as I didn't check that this function was not on Bioconductor. Your view is perfect.
Sorry for trouble.
