### ISSUE TITLE
Save PlotStars command

### ISSUE THREAD

**Issue by fbenedett** [SofieVG/FlowSOM#25]
Hello,

I am trying to save a "PlotStars" on a png file but to do that I need the command more than the GUI way.  Is there a way to do that?

**Comment by SofieVG** [comment]
Hi Fabrizio,

You can make use of the png function of R (see
https://www.rdocumentation.org/packages/grDevices/versions/3.4.1/topics/png)
The code would look something like
png("my_file_name.png", width = 2000, height = 1000)
PlotStars(fsom, ...)
dev.off()

In general, I might recommend saving the tree to pdf, because this way you
keep high quality to zoom in (or edit colors / position of the legend etc
in other editors like inkscape).
This works the same way, only note that the width and height should then be
given in inches instead of pixels (so maybe 12 by 8 instead of thousands).

I hope this helps!
Kind regards,
Sofie

**Comment by fbenedett** [comment]
Thank you for your reply.  I tried what you suggested but it doesn't work...
I am currently using Rmarkdown in my Rstudio and when I try that command there is an error.
Please, see the image in attachment.  In the image is also possible to see the "PlotStars" without the png, and in this case it shows what it should.
![Screenshot from 2019-05-23 15-56-24](https://user-images.githubusercontent.com/11632090/58258870-c87f2e80-7d73-11e9-95ba-7ac66e74f84b.png)
Maybe I should bang my head in the Rmarkdown git hub instead of bothering you here.

**Comment by SofieVG** [comment]
Are you running the whole codeblock at once? If you do it line by line, the
notebook itself will call something like dev.off() after every line, so
then indeed it won't work. So you should either click on the green arrow or
select the three lines at once and press ctrl enter.

**Comment by fbenedett** [comment]
Thank you, with the arrow it worked  :)
And sorry for bothering for a rmarkdown problem.
