### ISSUE TITLE
Question som$map$codes

### ISSUE THREAD

**Issue by fbenedett** [SofieVG/FlowSOM#40]
Hello,

I am a bit struggling to understand the details of FlowSOM.   Imagine that you have a flow set that you have clustered.
som <- BuildSOM(fsom, colsToUse = some_colors )
cell_clustering_som <- som$map$mapping[,1]

So, cell_clustering_som tell us to which cluster a given line of the flow set belongs.
If I have:
expr_mat=fsApply(fsom,exprs)

What is the relation between expr_mat and som$map$codes?
I was thinking that "codes" represent the average expression for a given cluster, so if I do (for instance for cluster 1):
apply(expr_mat[cell_clustering_som==1, some_colors],2,mean))
I should get the "codes" for cluster 1, but I don't.

Simply, is there a way to get som$map$codes from cell_clustering_som and expr_mat?

Thank you for any answer.

**Comment by SofieVG** [comment]
Dear Fabrizio,

The values you get with the method you describe should correspond to
som$map$medianValues
The codes, however, are the ones gained by training the self-organizing
map. This means that during training, one by one cells are presented to the
current cluster centers, the closest one is determined, and this one and
the ones near it in the grid are updated so the value shifts closer to the
value of the cell presented (how much closer etc depending on the algorithm
parameters). By iterating this procedure many times (default ten times the
amount of cells presented) the cluster centers move to dense regions in the
high-dimensional space. In the end, a final iteration is made through all
cells to assign them to the closest cluster center without updating
the center values anymore. So while these codes representing the cluster
centers will be near the cells assigned to it, it will not exactly
correspond to the mean / median you are computing. In the FlowSOM
visualisations, we make use of the median values per cluster rather than
these code values.

Hope this helps!
Kind regards,
Sofie

**Comment by fbenedett** [comment]
Thank you for your explanation and your time.
