### ISSUE TITLE
All populations not exported into FlowJo

### ISSUE THREAD

**Issue by ksadtle3** [SofieVG/FlowSOM#9]
Hi, I am having an issue when using the FlowJo plugin where I select 40 metaclusters, but am only getting 20 populations (0-19) exported into FlowJo as opposed to a number closer to 40. Everything else runs fine, its just the population export -- this might be a FlowJo issue, but I am not sure. Thanks!

**Comment by SofieVG** [comment]
Hi,

I tested it out and can replicate your issue. However, all FlowSOM results which are saved (e.g. the colors in the tree and the csv files) seem to point that FlowSOM correctly generated 40 metaclusters. Therefore, I think this is a FlowJo issue and I have contacted the developer of the FlowSOM-FlowJo plugin to look into this.

Best wishes,
Sofie

**Comment by JosefFlowJo** [comment]
Hi,

The output of the FlowSOM FlowJo plugin is a derived parameter with the FlowSOM metacluster number. That is passed from the plugin back to FlowJo. Then FlowJo runs its default processing of the derived parameter, which is essentially basic clustering on it, and I believe there is a limit of 20 populations that can be generated this way.

The derived parameter with the FlowSOM metacluster number is there though, and that has distinct values for all the 40 metaclusters, so one can manually gate on the histogram to get all the 40 FlowSOM metaclusters as separate populations... but yes, admittedly this can be labour intensive for large number of metaclusters. I believe we have ways to solve that by applying another plugin on top of FlowSOM, or we could possibly extend the FlowSOM so that it returns the populations directly rather than just the derived parameter. I'll look into it, but it definitely isn't a problem with FlowSOM itself, so I'd suggest we take the follow up out of here and maybe you can email me directly?

Thanks,
Josef

-- 
Josef Spidlen, Ph.D. | josefs@flowjo.com
Director of Bioinformatics | FlowJo, LLC
385 Williamson Way
Ashland, OR 97520  USA
